### ISSUE TITLE
won't launch serve

### ISSUE THREAD

**Issue by peterclemenko** [mdbootstrap/Admin-Dashboard-Template-Angular-Bootstrap#5]
It fails to compile and won't serve the dash

 ng serve -o
Your global Angular CLI version (8.1.2) is greater than your local
version (8.0.6). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Object prototype may only be an Object or null: undefined
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at Object.__extends (C:\Users\aoighost\Desktop\Admin-Dashboard-Template-Angular-Bootstrap\node_modules\tslib\tslib.js:65:9)
    at C:\Users\aoighost\Desktop\Admin-Dashboard-Template-Angular-Bootstrap\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:115:17
    at C:\Users\aoighost\Desktop\Admin-Dashboard-Template-Angular-Bootstrap\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:314:6
    at C:\Users\aoighost\Desktop\Admin-Dashboard-Template-Angular-Bootstrap\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:3:17
    at Object.<anonymous> (C:\Users\aoighost\Desktop\Admin-Dashboard-Template-Angular-Bootstrap\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at C:\Users\aoighost\Desktop\Admin-Dashboard-Template-Angular-Bootstrap\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\transform.js:20:22
    at C:\Users\aoighost\Desktop\Admin-Dashboard-Template-Angular-Bootstrap\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\transform.js:10:17
    at Object.<anonymous> (C:\Users\aoighost\Desktop\Admin-Dashboard-Template-Angular-Bootstrap\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\transform.js:16:3)

**Comment by idzark** [comment]
Please try to downgrade angular/compiler-cli version. For example to 8.1.2.
